export const RBAC = {
  admin: {
    Counter: { canReadFields: ["*"], canWriteFields: ["*"] },
    User: { canReadFields: ["*"], canWriteFields: ["*"] },
    Customer: { canReadFields: ["*"], canWriteFields: ["*"] },
    Supplier: { canReadFields: ["*"], canWriteFields: ["*"] },
    RepairJob: { canReadFields: ["*"], canWriteFields: ["*"] },
    SparePartEntry: { canReadFields: ["*"], canWriteFields: ["*"] },
    SparePart: { canReadFields: ["*"], canWriteFields: ["*"] },
    Payment: { canReadFields: ["*"], canWriteFields: ["*"] },
    PaymentEntry: { canReadFields: ["*"], canWriteFields: ["*"] },
    RolePermission: { canReadFields: ["*"], canWriteFields: ["*"] },
  },
  manager: {
    Counter: { canReadFields: ["*"], canWriteFields: ["*"] },
    User: { canReadFields: ["*"], canWriteFields: ["*"] },
    Customer: { canReadFields: ["*"], canWriteFields: ["*"] },
    Supplier: { canReadFields: ["*"], canWriteFields: ["*"] },
    RepairJob: { canReadFields: ["*"], canWriteFields: ["*"] },
    SparePartEntry: { canReadFields: ["*"], canWriteFields: ["*"] },
    SparePart: { canReadFields: ["*"], canWriteFields: ["*"] },
    Payment: { canReadFields: ["*"], canWriteFields: ["*"] },
    PaymentEntry: { canReadFields: ["*"], canWriteFields: ["*"] },
    RolePermission: { canReadFields: ["*"], canWriteFields: ["*"] },
  },
  technician: {
    Counter: { canReadFields: ["*"], canWriteFields: ["*"] },
    User: { canReadFields: ["*"], canWriteFields: ["*"] },
    Customer: { canReadFields: ["*"], canWriteFields: ["*"] },
    Supplier: { canReadFields: ["*"], canWriteFields: ["*"] },
    RepairJob: { canReadFields: ["*"], canWriteFields: ["*"] },
    SparePartEntry: { canReadFields: ["*"], canWriteFields: ["*"] },
    SparePart: { canReadFields: ["*"], canWriteFields: ["*"] },
    Payment: { canReadFields: ["*"], canWriteFields: ["*"] },
    PaymentEntry: { canReadFields: ["*"], canWriteFields: ["*"] },
    RolePermission: { canReadFields: ["*"], canWriteFields: ["*"] },
  },
};
